<a href="https://colab.research.google.com/github/NeisserMS/M1_Python_Colab/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *Practicando* con Pandas:

## Importando un Dataset de Ventas (Bata)


In [1]:
import pandas as pd

In [ ]:
#@title Dataset de ventas
url = ("https://raw.githubusercontent.com/NeisserMS/M1_Python_Colab/main/VentasBata.csv")
df = pd.read_csv(url, sep=';')
df.head((10))

id_Venta  id_Cliente  id_producto  ...        Mes Vendedor    Servicio
0         1           1            1  ...     Agosto  Neisser      Pedido
1         2           2            1  ...  Diciembre    Kenny       Venta
2         3           2            2  ...     Agosto  Takashi       Venta
3         4           1            2  ...      Julio    Kevin  Devolucion
4         5           1            3  ...      Junio  Neisser       Venta
5         6           2            1  ...       Mayo    Kenny      Pedido
6         7           3            2  ...      Julio  Takashi      Pedido
7         8           3            3  ...      Junio    Kevin       Venta
8         9           4            4  ...      Abril  Neisser  Devolucion
9        10           4            5  ...      Abril  Neisser       Venta

[10 rows x 12 columns]

In [ ]:
print(pd.__version__)

1.1.5


In [7]:
se = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(se)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
se.values

array([1, 2, 3, 4, 5])

In [24]:
se.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
type(se)

pandas.core.series.Series

In [ ]:
type(se.values)

numpy.ndarray

In [ ]:
s1 = pd.Series({'a':"Guantes", 'b':"Zapatos", 'c':"Buzo", 'd':"Polo", 'e':"Gorra"})
s1

a    Guantes
b    Zapatos
c       Buzo
d       Polo
e      Gorra
dtype: object

In [ ]:
s1.values

array([10, 11, 12, 13])

In [ ]:
s1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

### Trabajando con Data Frame

In [ ]:
DataFrame1 = pd.DataFrame({'Precio': se, 'Producto': s1})
DataFrame1

Precio Producto
a       1  Guantes
b       2  Zapatos
c       3     Buzo
d       4     Polo
e       5    Gorra

In [ ]:
DataFrame1.T

a        b     c     d      e
Precio          1        2     3     4      5
Producto  Guantes  Zapatos  Buzo  Polo  Gorra

In [ ]:
DataFrame1.values

array([[1, 'Guantes'],
       [2, 'Zapatos'],
       [3, 'Buzo'],
       [4, 'Polo'],
       [5, 'Gorra']], dtype=object)

In [ ]:
DataFrame1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
DataFrame1.columns

Index(['Precio', 'Producto'], dtype='object')

In [ ]:
#@title Obteniendo un valor espefiico:
DataFrame1.values[2,1]

'Buzo'

In [4]:
sa = pd.Series({'a':10,'b':20,'c':30,'d':40,'e':50})

In [ ]:
sa

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [9]:
DataFrame2 = pd.DataFrame({'Serie 1': se, 'Serie 2': sa})
DataFrame2

Serie 1  Serie 2
a        1       10
b        2       20
c        3       30
d        4       40
e        5       50

In [10]:
DataFrame2['Suma series'] = DataFrame2['Serie 1'] + DataFrame2 ['Serie 2']

DataFrame2

Serie 1  Serie 2  Suma series
a        1       10           11
b        2       20           22
c        3       30           33
d        4       40           44
e        5       50           55

In [11]:
del DataFrame2['Suma series']
DataFrame2

Serie 1  Serie 2
a        1       10
b        2       20
c        3       30
d        4       40
e        5       50

In [12]:
DataFrame2.loc['a']

Serie 1     1
Serie 2    10
Name: a, dtype: int64

In [13]:
DataFrame2.loc[['a', 'd']]

Serie 1  Serie 2
a        1       10
d        4       40

In [14]:
DataFrame2.iloc[0]

Serie 1     1
Serie 2    10
Name: a, dtype: int64

In [15]:
dataFrameSearch = DataFrame2[DataFrame2['Serie 1']>=4]
dataFrameSearch

Serie 1  Serie 2
d        4       40
e        5       50

In [16]:
minutes = pd.Series([60,45,30,45,45,4500], index=[0,1,2,3,4,5])
rate = pd.Series([4,4,8,7,10], index=[0,1,3,4,5])
ask = pd.Series([1,'cero',2,2,3], index=[1,2,3,4,5])
dfClass = pd.DataFrame({'Time':minutes, 'Rate':rate, 'Ask':ask})
dfClass



Time  Rate   Ask
0    60   4.0   NaN
1    45   4.0     1
2    30   NaN  cero
3    45   8.0     2
4    45   7.0     2
5  4500  10.0     3

In [17]:
dfNewClass = dfClass.dropna()
dfNewClass

Time  Rate Ask
1    45   4.0   1
3    45   8.0   2
4    45   7.0   2
5  4500  10.0   3

In [19]:
dfClass

Time  Rate   Ask
0    60   4.0   NaN
1    45   4.0     1
2    30   NaN  cero
3    45   8.0     2
4    45   7.0     2
5  4500  10.0     3

In [23]:
dfClass.dropna(inplace= True)
dfClass

Time  Rate Ask
1    45   4.0   1
3    45   8.0   2
4    45   7.0   2
5  4500  10.0   3

Actualizamos el dataframe que teniamos para poder llenar los datos nulos:


In [27]:

dfClass = pd.DataFrame({'Time': minutes, 'Rate':rate, 'Ask':ask})
dfClass

Time  Rate   Ask
0    60   4.0   NaN
1    45   4.0     1
2    30   NaN  cero
3    45   8.0     2
4    45   7.0     2
5  4500  10.0     3

In [28]:
dfClass.fillna(333, inplace=True)
dfClass

Time   Rate   Ask
0    60    4.0   333
1    45    4.0     1
2    30  333.0  cero
3    45    8.0     2
4    45    7.0     2
5  4500   10.0     3

In [29]:
dfClass = pd.DataFrame({'Time': minutes, 'Rate':rate, 'Ask':ask})
dfClass

Time  Rate   Ask
0    60   4.0   NaN
1    45   4.0     1
2    30   NaN  cero
3    45   8.0     2
4    45   7.0     2
5  4500  10.0     3

In [30]:
dfClass['Rate'].fillna(7, inplace = True)
dfClass

Time  Rate   Ask
0    60   4.0   NaN
1    45   4.0     1
2    30   7.0  cero
3    45   8.0     2
4    45   7.0     2
5  4500  10.0     3

### Mean


In [31]:

dfClass = pd.DataFrame({'Time': minutes, 'Rate':rate, 'Ask':ask})
dfClass

Time  Rate   Ask
0    60   4.0   NaN
1    45   4.0     1
2    30   NaN  cero
3    45   8.0     2
4    45   7.0     2
5  4500  10.0     3

In [32]:
mean = dfClass['Rate'].mean()
mean

6.6

### Median

In [34]:
median = dfClass['Rate'].median()
median

7.0

### Mode

In [36]:
mode = dfClass['Rate'].mode()
mode

0    4.0
dtype: float64

In [38]:
dfClass.Ask[dfClass.Ask=='cero']=0
dfClass

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Time  Rate  Ask
0    60   4.0  NaN
1    45   4.0    1
2    30   NaN    0
3    45   8.0    2
4    45   7.0    2
5  4500  10.0    3

In [40]:
dfClass.loc[5,'Time']=45
dfClass

Time  Rate  Ask
0    60   4.0  NaN
1    45   4.0    1
2    30   NaN    0
3    45   8.0    2
4    45   7.0    2
5    45  10.0    3

### Eliminar Datos duplicados:


In [42]:

dfClass.duplicated()


0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

#### Duplicaremos algunos datos:

In [45]:
dfClass.loc[6, 'Time'] = 45
dfClass.loc[6, 'Rate'] = 7
dfClass.loc[6, 'Ask'] = 2
dfClass

Time  Rate  Ask
0  60.0   4.0  NaN
1  45.0   4.0    1
2  30.0   NaN    0
3  45.0   8.0    2
4  45.0   7.0    2
5  45.0  10.0    3
6  45.0   7.0    2

In [46]:
dfClass.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [47]:
dfClass.drop_duplicates(inplace=True)
dfClass

Time  Rate  Ask
0  60.0   4.0  NaN
1  45.0   4.0    1
2  30.0   NaN    0
3  45.0   8.0    2
4  45.0   7.0    2
5  45.0  10.0    3